server.port: 8083

spring.kafka:
  bootstrap-server: localhost:9092
  value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy
  listener:
    ack-mode: MANUAL_IMMEDIATE
    concurrency: 11
    producer:
      client-id: creditodebito
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      client-id: creditodebito
      group-id: creditodebito
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      enable-auto-commit: false
      auto-offset-reset: latest

creditodebito:
  kafka:
    consumer:
      topics: comando-credito,comando-debito
    producer:
      topic-atutalizado: credito-processado,debito-processado